hydra:
  run:
    dir: outputs/${experiment_name}/${training_cfg.SetupNN.model_name}/${now:%Y-%m-%d_%H-%M-%S}
defaults:
  - ../../configs@_global_.training_cfg: training_v1
  - _self_

# mlflow
path_to_mlflow: mlruns
experiment_name: ???

# setup
scaling_cfg: ../../configs/ShuffleMergeSpectral_trainingSamples-2_files_0_498.json # for DataLoader initialisation
gpu_cfg:
  gpu_mem  : 7 # in Gb
  gpu_index: 0

# logs
log_suffix: step1
