config:
  params:
    cmsRunOptions: "sampleType=MC,era=Run3"

TauGun_E-5to10: /TauGun_E-5to10_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v2/MINIAODSIM
TauGun_E-10to100: /TauGun_E-10to100_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v2/MINIAODSIM
TauGun_E-100to3000: /TauGun_E-100to3000_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v1-v2/MINIAODSIM
