config:
  params:
    cmsRunOptions: "sampleType=MC,era=Run3"

QCD_PT-1000to4000: /QCD_PT-1000to1400_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-1000to4000_ext1: /QCD_PT-1000to1400_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-120to170: /QCD_PT-120to170_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-120to170_ext1: /QCD_PT-120to170_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-1400to1800: /QCD_PT-1400to1800_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-1400to1800_ext1: /QCD_PT-1400to1800_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-170to300: /QCD_PT-170to300_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-170to300_ext1: /QCD_PT-170to300_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-1800to2400: /QCD_PT-1800to2400_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-1800to2400_ext1: /QCD_PT-1800to2400_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-2400to3200: /QCD_PT-2400to3200_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-2400to3200_ext1: /QCD_PT-2400to3200_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-300to470: /QCD_PT-300to470_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-300to470_ext1: /QCD_PT-300to470_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-3200: /QCD_PT-3200_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-3200_ext1: /QCD_PT-3200_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-470to600: /QCD_PT-470to600_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-470to600_ext1: /QCD_PT-470to600_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-50to80: /QCD_PT-50to80_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-600to800: /QCD_PT-600to800_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-600to800_ext1: /QCD_PT-600to800_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM 
QCD_PT-800to1000: /QCD_PT-800to1000_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
QCD_PT-800to1000_ext1: /QCD_PT-800to1000_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12_ext1-v2/MINIAODSIM
QCD_PT-80to120: /QCD_PT-80to120_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv3-124X_mcRun3_2022_realistic_postEE_v12-v2/MINIAODSIM
