name: DeepTau vs. ${vs_type} (Run 3)
pred_column_prefix: node_
pred_column: ${.pred_column_prefix}${vs_type} # column in internally created pd.DataFrame to be used for metrics computation  
raw: True
from_tuple: False
color: orange
