# general
name: DeepBoostedTau vs. ${vs_type} (V1_0_0)
color: orange
dashed: False
raw: True

# prediction/target columns
pred_column_prefix: node_
pred_column: ${.pred_column_prefix}${vs_type} # column in internally created pd.DataFrame to be used for metrics computation  
target_column_prefix: node_

# WPs
wp_from: null