name: MVA vs. jets (JINST 13 (2018) P10005)
pred_column: byIsolationMVArun2017v2DBoldDMwLT2017
raw: False
from_tuple: True
color: green
working_points: 
  - ${wp_name_to_index.VVLoose}
  - ${wp_name_to_index.VLoose}
  - ${wp_name_to_index.Loose}
  - ${wp_name_to_index.Medium}
  - ${wp_name_to_index.Tight}
  - ${wp_name_to_index.VTight}
  - ${wp_name_to_index.VVTight}
wp_column: byIsolationMVArun2017v2DBoldDMwLT2017