Setup:
    
    debug                : False

    n_tau                :  500 # number of candidates in one batch 
    n_threads            :  1
    input_dir            : "/nfs/dust/cms/user/mykytaua/softDeepTau/RecoML/DisTauTag/TauMLTools/FlatMerge-output-v3/"
    spectrum_to_reweight : "/nfs/dust/cms/user/mykytaua/softDeepTau/RecoML/DisTauTag/TauMLTools/FlatMerge-output-v3-spectrum/ShuffleMergeFlat.root"
    dataloader_core      : "TauMLTools/Training/interface/DataLoaderDisTauTag_main.h"
    jet_types_names      : { "0":"jet", "1":"tau",  }
    output_classes       : 2 #number of elements in jet_types_names
    recompute_jet_type   : True
    weight_thr           : 1000
    include_mismatched   : False

    # here define variables for the Histogram_2D class
    yaxis                : [
      20. , 30. , 40. , 50. , 60. , 70. , 80. , 90. , 100., 110.,
      120., 130., 140., 150., 160., 170., 180., 190., 200.,
      250., 300., 350., 400., 450., 500., 600., 700., 1000.
    ]
    xaxis_list           : [
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #20-30
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #30-40
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #40-50
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #50-60
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #60-70
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #70-80
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #80-90
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #90-100
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #100-110
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #110-120
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #120-130
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #130-140
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #140-150
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #150-160
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #160-170
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #170-180
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #180-190
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #190-200
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #200-250
      [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4], #250-300
      [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.5, 1.8, 2.1, 2.4], #300-350
      [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.5, 1.8, 2.1, 2.4], #350-400
      [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.5, 1.8, 2.1, 2.4], #400-450
      [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.5, 1.8, 2.1, 2.4], #450-500
      [0.0, 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.4], #500-600
      [0.0, 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.4], #600-700
      [0.0, 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.4], #700-1000
                            ]
    xmin                 : 0
    xmax                 : 2.4

SetupBaseNN:
    
    model_name           : "TauJetTag"
    n_batches            : -1
    n_batches_val        : -1
    n_batches_log        : 100
    epoch                : 0
    n_epochs             : 5
    validation_split     : 0.2
    max_queue_size       : 10
    n_load_workers       : 6
    learning_rate        : 0.001

SetupSNN:

    conv1D_params        : [50, 50]
    conv_params          : [ # [dim, n_output]
                              [2, 50],
                              [2, 50],
                              [2, 50],
                              [2, 100],
                              [2, 100],
                              [2, 100],
                              [2, 170],
                              [2, 170],
                              [2, 170],
                           ]
    dense_params         : [170, 170]
    wiring_period        : 3
    dropout_rate         : 0.1 
    regu_rate            : 0

SetupParticleNet:

    conv_params          : [ #[K, [C1, C2, C3]]
                              [16, [64,  64,  64]],
                              [16, [128, 128, 128]],
                              [16, [256, 256, 256]]
                           ]
    dense_params         : [256]
    conv_pooling         : "average"
    dropout_rate         : 0.1

CellObjectType : [ PfCand,  PfCandCategorical ] # All Cell Objects

# Embedded Cell Objects:
# For the features inside this group embedding will be used
# Embedding parameters will be taken from the cooresponding feature list:
# e.g: -> pfCand_particleType  : [ null, null, "categorical", 0, 8]
# cooresponding embedding parameters: -> tf.keras.layers.Embedding(8,  2)
EmbeddedCellObjectType : [ PfCandCategorical ]

SequenceLength:
    PfCand : 50
    PfCandCategorical : 50

Scaling_setup:
    # --------------------------------------------------------
    file_path: '/nfs/dust/cms/user/mykytaua/softDeepTau/RecoML/DisTauTag/TauMLTools/FlatMerge-output/*.root' # input files to be used for computation of scaling params
    output_json_folder: 'output_json' # directory where json files with scaling params will be stored
    file_range: [0,50] # range of files in the sorted `file_path` to be processed, right endpoint excluded; -1 to run on all files from file_path
    tree_name: taus # TTree name in input files to be read
    log_step: 10 # will make a snapshot of scaling parameters per this number of input files
    version: 'DisTauTag_v1' # string to be added to a json filename

    # --------------------------------------------------------
    # aliases for selection cuts
    selection:
      - &mpi -3.141592653589793
      - &pi 3.141592653589793
      - &jet_valid 'jet_index >= 0'
      - &cut_pfCand_dxy         '(jet_index >= 0) & (pfCand_hasTrackDetails == 1) & (pfCand_dxy>-10000) & (pfCand_dxy<10000)'
      - &cut_pfCand_dxy_error   '(jet_index >= 0) & (pfCand_hasTrackDetails == 1) & (pfCand_dxy_error>-10000) & (pfCand_dxy_error<10000)'
      - &cut_pfCand_dz          '(jet_index >= 0) & (pfCand_hasTrackDetails == 1) & (pfCand_dz>-10000) & (pfCand_dz<10000)'
      - &cut_pfCand_dz_error    '(jet_index >= 0) & (pfCand_hasTrackDetails == 1) & (pfCand_dz_error>-10000) & (pfCand_dz_error<10000)'
      - &cut_pfCand_track_chi2  '(jet_index >= 0) & (pfCand_hasTrackDetails == 1) & (pfCand_track_chi2>-10000) & (pfCand_track_chi2<10000)'
      - &cut_pfCand_track_ndof  '(jet_index >= 0) & (pfCand_hasTrackDetails == 1) & (pfCand_track_ndof>-10000) & (pfCand_track_ndof<10000)'
      # - &hasTrackDetails_track_ndof '(pfCand_hasTrackDetails == 1)  & (pfCand_track_ndof > 0)'

        # parameters for inner/outer tau cones' definition
    cone_definition:
      null

    cone_selection:

      PfCand: 
        var_names:
          eta: pfCand_eta
          phi: pfCand_phi
        cone_types: [null]

      PfCandCategorical: 
        var_names:
          eta: pfCand_eta
          phi: pfCand_phi
        cone_types: [null]


Features_all :

    PfCand :
          - pfCand_valid                : [ *jet_valid, null, "categorical"]
          - pfCand_pt                   : [ *jet_valid, null, "linear", 0.0, 100.0 ]
          - pfCand_eta                  : [ *jet_valid, null, "linear", -3.0, 3.0 ]
          - pfCand_phi                  : [ *jet_valid, null, "linear", *mpi, *pi ]
          - pfCand_mass                 : [ *jet_valid, null, "normal", -5, 5 ]
          - pfCand_charge               : [ *jet_valid, null, "categorical" ]
          - pfCand_puppiWeight          : [ *jet_valid, null, "no_scaling" ]
          - pfCand_puppiWeightNoLep     : [ *jet_valid, null, "no_scaling" ]
          - pfCand_lostInnerHits        : [ *jet_valid, null, "linear", 0, 10 ] # ???
          - pfCand_nPixelHits           : [ *jet_valid, null, "linear", 0, 10 ]
          - pfCand_nHits                : [ *jet_valid, null, "normal", -5, 5 ]
          - pfCand_hasTrackDetails      : [ *jet_valid, null, "categorical" ]
          - pfCand_dxy                  : [ *cut_pfCand_dxy, null, "normal", -5, 5 ]
          - pfCand_dxy_error            : [ *cut_pfCand_dxy_error, null, "normal", -5, 5 ]
          - pfCand_dz                   : [ *cut_pfCand_dz, null, "normal", -5, 5 ]
          - pfCand_dz_error             : [ *cut_pfCand_dz_error, null, "normal", -5, 5 ]
          - pfCand_track_chi2           : [ *cut_pfCand_track_chi2, null, "normal", -5, 5 ]
          - pfCand_track_ndof           : [ *cut_pfCand_track_ndof, null, "normal", -5, 5 ]
          - pfCand_caloFraction         : [ *jet_valid, null, "linear", 0.0, 1.0 ]
          - pfCand_hcalFraction         : [ *jet_valid, null, "linear", 0.0, 1.0 ]
          - pfCand_rawCaloFraction      : [ *jet_valid, null, "linear", 0.0, 2.6 ]
          - pfCand_rawHcalFraction      : [ *jet_valid, null, "linear", 0.0, 1.0 ]

          - pfCand_deta                 : [ *jet_valid, {"pfCand_ele_deta": "pfCand_eta - jet_eta"}, "no_scaling" ]
          - pfCand_dphi                 : [ *jet_valid, {"pfCand_ele_dphi": "pfCand_phi - jet_phi"}, "no_scaling" ]

    PfCandCategorical:

          - pfCand_particleType         : [ *jet_valid, null, "categorical", 8, 2]
          - pfCand_pvAssociationQuality : [ *jet_valid, null, "categorical", 8, 2]
          - pfCand_fromPV               : [ *jet_valid, null, "categorical", 4, 2]

Features_disable :
    PfCand : [ ]
    PfCandCategorical : [ ]