config:
    params:
      cmsRunOptions: "sampleType=MC,era=Run2_2018"

  bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8: /bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
  bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8: /bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8/RunIISummer20UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v2/MINIAODSIM
  bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8: /bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
  