config:
  params:
    sampleType: data
    era: Run2_2018
  #lumiMask: /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/Legacy_2018/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt

EGamma_Run2018A: /EGamma/Run2018A-UL2018_MiniAODv2_GT36-v1/MINIAOD
EGamma_Run2018B: /EGamma/Run2018B-UL2018_MiniAODv2-v1/MINIAOD
EGamma_Run2018C: /EGamma/Run2018C-UL2018_MiniAODv2_GT36-v1/MINIAOD
EGamma_Run2018D: /EGamma/Run2018D-UL2018_MiniAODv2-v2/MINIAOD

SingleMuon_Run2018A: /SingleMuon/Run2018A-UL2018_MiniAODv2_GT36-v1/MINIAOD
SingleMuon_Run2018B: /SingleMuon/Run2018B-UL2018_MiniAODv2_GT36-v1/MINIAOD
SingleMuon_Run2018C: /SingleMuon/Run2018C-UL2018_MiniAODv2_GT36-v2/MINIAOD
SingleMuon_Run2018D: /SingleMuon/Run2018D-UL2018_MiniAODv2_GT36-v1/MINIAOD

Tau_Run2018A: /Tau/Run2018A-UL2018_MiniAODv2-v1/MINIAOD
Tau_Run2018B: /Tau/Run2018B-UL2018_MiniAODv2_GT36-v1/MINIAOD
Tau_Run2018C: /Tau/Run2018C-UL2018_MiniAODv2_GT36-v1/MINIAOD
Tau_Run2018D:
  inputDataset: /Tau/Run2018D-UL2018_MiniAODv2-v1/MINIAOD
  ignoreFiles:
    - /store/data/Run2018D/Tau/MINIAOD/UL2018_MiniAODv2-v1/240000/85725A5B-F5E3-7A44-BDBD-7812E48A9733.root

DoubleMuon_Run2018A: /DoubleMuon/Run2018A-UL2018_MiniAODv2_GT36-v1/MINIAOD
DoubleMuon_Run2018B: /DoubleMuon/Run2018B-UL2018_MiniAODv2_GT36-v1/MINIAOD
DoubleMuon_Run2018C: /DoubleMuon/Run2018C-UL2018_MiniAODv2_GT36-v1/MINIAOD
DoubleMuon_Run2018D: /DoubleMuon/Run2018D-UL2018_MiniAODv2_GT36-v1/MINIAOD

JetHT_Run2018A: /JetHT/Run2018A-UL2018_MiniAODv2_GT36-v1/MINIAOD
JetHT_Run2018B: /JetHT/Run2018B-UL2018_MiniAODv2_GT36-v1/MINIAOD
JetHT_Run2018C: /JetHT/Run2018C-UL2018_MiniAODv2_GT36-v1/MINIAOD
JetHT_Run2018D: /JetHT/Run2018D-UL2018_MiniAODv2-v2/MINIAOD

MET_Run2018A: /MET/Run2018A-UL2018_MiniAODv2_GT36-v1/MINIAOD
MET_Run2018B: /MET/Run2018B-UL2018_MiniAODv2_GT36-v1/MINIAOD
MET_Run2018C: /MET/Run2018C-UL2018_MiniAODv2-v1/MINIAOD
MET_Run2018D: /MET/Run2018D-UL2018_MiniAODv2-v1/MINIAOD