# basic imports
defaults:
  - discriminator: TauTransformer_RetraceDeepTau
  - selection
  - _self_

# mflow run info
path_to_mlflow: /work/tvoigtlaender/thesis/ml/mlruns
experiment_name: TauT_TV_Thesis
run_name:
  - 2025_mar_ensemble_2_r_2
  - 2025_mar_ensemble_2_r_3
  - 2025_mar_ensemble_2_r_4
  - 2025_mar_ensemble_2_r_5
  - 2025_mar_ensemble_2_r_6
  - 2025_mar_ensemble_2_r_7
  - 2025_mar_ensemble_2_r_8
  - 2025_mar_ensemble_2_r_9
  - 2025_mar_ensemble_2_o_1
  - 2025_mar_ensemble_2_o_2
  - 2025_mar_ensemble_2_o_3
  - 2025_mar_scaling_6_1
  - 2025_mar_scaling_6_2
  - 2025_mar_scaling_6_3
  - 2025_mar_scaling_6_4
  - 2025_mar_scaling_6_5
  - 2025_mar_scaling_6_6
  - 2025_mar_scaling_6_7
  - 2025_mar_scaling_6_8
  - 2025_mar_scaling_6b_1
  - 2025_apr_full_dataset_1_1
  - 2025_apr_full_dataset_cut_rand_2_1
  - 2025_apr_full_dataset_cut_rand_2_2
  - 2025_apr_full_dataset_cut_rand_2_3
  - 2025_apr_full_dataset_cut_rand_2_4
  - 2025_apr_full_dataset_cut_rand_2_5
  - 2025_mar_rcut_2_1
  - 2025_apr_full_dataset_1_1_at7
  - 2025_apr_full_dataset_1_1_at21
  - 2025_apr_full_dataset_1_1_at47

# phase space region
vs_types:
  - jet
  - e
  - mu
dataset_alias: # alias to reference a mixture of input_samples below, e.g. tau_DY_jet_TT
  - tau_ggH_jet_TT
  - tau_ggH_e_DY
  - tau_ggH_mu_DY
pt_bins: [[20, 100]]
eta_bins: [[0, 2.3]]
dm_bins: [[0, 1, 10, 11]]

# selection
input_branches: [ 'tau_pt', 'tau_eta', 'tau_decayMode' , 'tau_dz'] # add here WP branches if necessary
cuts: "(${apply_dm_cuts}) and (abs(tau_dz) < 0.2)"
WPs_to_require: null # null to not apply WP as selection
# WPs_to_require: ### example for vs. jet
#   e: VVVLoose
#   mu: VLoose

# inputs/paths
input_samples: # "sample_alias": [list of strings with tau types to be selected]
  GluGluHToTauTau_M125: ['tau']
  DYJetsToLL_M-50-amcatnloFXFX_ext2: ["e", "mu"]
  TTToSemiLeptonic: ["jet"]
path_to_input: null
# path_to_pred: '${path_to_mlflow}/{experiment_id}/{run_id}/artifacts/predictions/{sample_alias}/*/predictions.h5'
pred_files:
  TTToSemiLeptonic:
    - "eventTuple_1-1/predictions.h5"
    - "eventTuple_1-10/predictions.h5"
    - "eventTuple_1-100/predictions.h5"
    - "eventTuple_1-1000/predictions.h5"
    - "eventTuple_1-1001/predictions.h5"
    - "eventTuple_1-1002/predictions.h5"
    - "eventTuple_1-1003/predictions.h5"
    - "eventTuple_1-1004/predictions.h5"
    - "eventTuple_1-1005/predictions.h5"
    - "eventTuple_1-1006/predictions.h5"
    - "eventTuple_1-1007/predictions.h5"
    - "eventTuple_1-1008/predictions.h5"
    - "eventTuple_1-1009/predictions.h5"
    - "eventTuple_1-101/predictions.h5"
    - "eventTuple_1-1010/predictions.h5"
    - "eventTuple_1-1011/predictions.h5"
    - "eventTuple_1-1012/predictions.h5"
    - "eventTuple_1-1013/predictions.h5"
    - "eventTuple_1-1014/predictions.h5"
    - "eventTuple_1-1015/predictions.h5"
    - "eventTuple_1-102/predictions.h5"
    - "eventTuple_1-103/predictions.h5"
    - "eventTuple_1-104/predictions.h5"
    - "eventTuple_1-11/predictions.h5"
    - "eventTuple_1-12/predictions.h5"
    - "eventTuple_1-120/predictions.h5"
    - "eventTuple_1-121/predictions.h5"
    - "eventTuple_1-122/predictions.h5"
    - "eventTuple_1-123/predictions.h5"
    - "eventTuple_1-124/predictions.h5"
    - "eventTuple_1-125/predictions.h5"
    - "eventTuple_1-126/predictions.h5"
    - "eventTuple_1-127/predictions.h5"
    - "eventTuple_1-128/predictions.h5"
    - "eventTuple_1-129/predictions.h5"
    - "eventTuple_1-13/predictions.h5"
    - "eventTuple_1-130/predictions.h5"
  DYJetsToLL_M-50-amcatnloFXFX_ext2:
    - "eventTuple_1/predictions.h5"
    - "eventTuple_10/predictions.h5"
    - "eventTuple_100/predictions.h5"
    - "eventTuple_1000/predictions.h5"
    - "eventTuple_1001/predictions.h5"
    - "eventTuple_1002/predictions.h5"
    - "eventTuple_1004/predictions.h5"
    - "eventTuple_1005/predictions.h5"
    - "eventTuple_1006/predictions.h5"
    - "eventTuple_1007/predictions.h5"
    - "eventTuple_1008/predictions.h5"
    - "eventTuple_1009/predictions.h5"
    - "eventTuple_101/predictions.h5"
    - "eventTuple_1010/predictions.h5"
    - "eventTuple_1012/predictions.h5"
    - "eventTuple_1013/predictions.h5"
    - "eventTuple_1014/predictions.h5"
    - "eventTuple_1015/predictions.h5"
    - "eventTuple_1016/predictions.h5"
    - "eventTuple_1017/predictions.h5"
    - "eventTuple_1019/predictions.h5"
    - "eventTuple_102/predictions.h5"
    - "eventTuple_1020/predictions.h5"
    - "eventTuple_1021/predictions.h5"
    - "eventTuple_1022/predictions.h5"
    - "eventTuple_1023/predictions.h5"
    - "eventTuple_1024/predictions.h5"
    - "eventTuple_1025/predictions.h5"
    - "eventTuple_1026/predictions.h5"
    - "eventTuple_1027/predictions.h5"
    - "eventTuple_1028/predictions.h5"
    - "eventTuple_1029/predictions.h5"
    - "eventTuple_103/predictions.h5"
    - "eventTuple_1030/predictions.h5"
    - "eventTuple_1031/predictions.h5"
    - "eventTuple_1032/predictions.h5"
    - "eventTuple_1034/predictions.h5"
    - "eventTuple_1035/predictions.h5"
    - "eventTuple_1036/predictions.h5"
    - "eventTuple_1037/predictions.h5"
    - "eventTuple_1038/predictions.h5"
    - "eventTuple_1039/predictions.h5"
    - "eventTuple_104/predictions.h5"
    - "eventTuple_1040/predictions.h5"
    - "eventTuple_1041/predictions.h5"
    - "eventTuple_1042/predictions.h5"
    - "eventTuple_1043/predictions.h5"
    - "eventTuple_1044/predictions.h5"
    - "eventTuple_1045/predictions.h5"
    - "eventTuple_1046/predictions.h5"
    - "eventTuple_1047/predictions.h5"
    - "eventTuple_1048/predictions.h5"
    - "eventTuple_1049/predictions.h5"
    - "eventTuple_105/predictions.h5"
    - "eventTuple_1050/predictions.h5"
    - "eventTuple_1051/predictions.h5"
    - "eventTuple_1052/predictions.h5"
    - "eventTuple_1053/predictions.h5"
    - "eventTuple_1054/predictions.h5"
    - "eventTuple_1055/predictions.h5"
    - "eventTuple_1056/predictions.h5"
    - "eventTuple_1057/predictions.h5"
    - "eventTuple_1058/predictions.h5"
    - "eventTuple_106/predictions.h5"
    - "eventTuple_1060/predictions.h5"
    - "eventTuple_1061/predictions.h5"
    - "eventTuple_1062/predictions.h5"
    - "eventTuple_1063/predictions.h5"
    - "eventTuple_1064/predictions.h5"
    - "eventTuple_1065/predictions.h5"
    - "eventTuple_1066/predictions.h5"
    - "eventTuple_1067/predictions.h5"
    - "eventTuple_1068/predictions.h5"
    - "eventTuple_1069/predictions.h5"
    - "eventTuple_107/predictions.h5"
    - "eventTuple_1070/predictions.h5"
    - "eventTuple_1071/predictions.h5"
    - "eventTuple_1072/predictions.h5"
    - "eventTuple_1073/predictions.h5"
    - "eventTuple_1074/predictions.h5"
    - "eventTuple_1075/predictions.h5"
    - "eventTuple_1076/predictions.h5"
    - "eventTuple_1077/predictions.h5"
    - "eventTuple_1078/predictions.h5"
    - "eventTuple_1079/predictions.h5"
    - "eventTuple_108/predictions.h5"
    - "eventTuple_1080/predictions.h5"
    - "eventTuple_1081/predictions.h5"
    - "eventTuple_1082/predictions.h5"
    - "eventTuple_1083/predictions.h5"
    - "eventTuple_1084/predictions.h5"
    - "eventTuple_1085/predictions.h5"
    - "eventTuple_1086/predictions.h5"
    - "eventTuple_1087/predictions.h5"
    - "eventTuple_1088/predictions.h5"
    - "eventTuple_1089/predictions.h5"
    - "eventTuple_109/predictions.h5"
    - "eventTuple_1090/predictions.h5"
    - "eventTuple_1091/predictions.h5"
    - "eventTuple_1092/predictions.h5"
    - "eventTuple_1093/predictions.h5"
    - "eventTuple_1094/predictions.h5"
    - "eventTuple_1095/predictions.h5"
    - "eventTuple_1096/predictions.h5"
    - "eventTuple_1097/predictions.h5"
    - "eventTuple_1098/predictions.h5"
    - "eventTuple_1099/predictions.h5"
  GluGluHToTauTau_M125:
    - "eventTuple_1/predictions.h5"
    - "eventTuple_1-1/predictions.h5"
    - "eventTuple_1-10/predictions.h5"
    - "eventTuple_1-11/predictions.h5"
    - "eventTuple_1-12/predictions.h5"
    - "eventTuple_1-13/predictions.h5"
    - "eventTuple_1-2/predictions.h5"
    - "eventTuple_1-3/predictions.h5"
    - "eventTuple_1-4/predictions.h5"
    - "eventTuple_1-5/predictions.h5"
    - "eventTuple_1-6/predictions.h5"
    - "eventTuple_1-7/predictions.h5"
    - "eventTuple_1-8/predictions.h5"
    - "eventTuple_1-9/predictions.h5"
    - "eventTuple_10/predictions.h5"
    - "eventTuple_11/predictions.h5"

# '${path_to_mlflow}/{experiment_id}/{run_id}/artifacts/predictions/{sample_alias}/*/predictions.h5'
path_to_target: null
path_to_weights_taus: null
path_to_weights_vs_type: null
output_file: performance_RetraceDeepTau.json

# misc.
roc_prune_decimal: # precision on TPR rounding
  e: 5
  mu: 5
  jet: 5
