config:
  params:
    cmsRunOptions: "sampleType=MC,era=Run3"

WtoTauNu_M-200: /WtoNuTau_M-200_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-100to200: /WtoTauNu_M-100to200_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-200to500: /WtoTauNu_M-200to500_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-500to1000: /WtoTauNu_M-500to1000_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-1000to2000: /WtoTauNu_M-1000to2000_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-2000to3000: /WtoTauNu_M-2000to3000_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-3000to4000: /WtoTauNu_M-3000to4000_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-4000to5000: /WtoTauNu_M-4000to5000_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-5000to6000: /WtoTauNu_M-5000to6000_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
WtoTauNu_M-6000: /WtoTauNu_M-6000_TuneCP5_13p6TeV_pythia8-tauola/Run3Summer22MiniAODv3-124X_mcRun3_2022_realistic_v12-v2/MINIAODSIM
