# # bitwise computation is not supported by pandas.eval() :(
# apply_legacy_cuts:
#   e: "(byIsolationMVArun2017v2DBoldDMwLT2017 & (1 << ${wp_name_to_index.VVLoose})) \
#               and (againstMuon3 & (1 << ${wp_name_to_index.Loose})) \
#               and (tau_decayMode != 5) & (tau_decayMode != 6)"
#   mu: "(byIsolationMVArun2017v2DBoldDMwLT2017 & (1 << ${wp_name_to_index.VVLoose})) \
#               and (againstElectronMVA6 & (1 << ${wp_name_to_index.VLoose})) \
#               and (tau_decayMode != 5) & (tau_decayMode != 6)"
#   jet: "(againstElectronMVA6 & (1 << ${wp_name_to_index.VLoose})) \
#               and (againstMuon3 & (1 << ${wp_name_to_index.Loose})) \
#               and (tau_decayMode != 5) & (tau_decayMode != 6)"
apply_deep_cuts:
  e: "(deepId_vs_jet > ${discriminator.deep_wp_thrs.jet.VVVLoose}) \
        and (deepId_vs_mu > ${discriminator.deep_wp_thrs.mu.VLoose})"
  mu: "(deepId_vs_e > ${discriminator.deep_wp_thrs.e.VVVLoose}) \
        and (deepId_vs_jet > ${discriminator.deep_wp_thrs.jet.VVVLoose})"
  jet: "(deepId_vs_e > ${discriminator.deep_wp_thrs.e.VVVLoose}) \
        and (deepId_vs_mu > ${discriminator.deep_wp_thrs.mu.VLoose})"
apply_dm_cuts: "(tau_decayMode != 5) & (tau_decayMode != 6)"
