name: DeepTau
column: deepId_vs_${vs_type}
raw: True
from_tuple: False
color: blue
working_points: 
  - ${wp_name_to_index.VVVLoose}
  - ${wp_name_to_index.VVLoose}
  - ${wp_name_to_index.VLoose}
  - ${wp_name_to_index.Loose}
  - ${wp_name_to_index.Medium}
  - ${wp_name_to_index.Tight}
  - ${wp_name_to_index.VTight}
  - ${wp_name_to_index.VVTight}
working_points_thrs: ${.deep_wp_thrs.${vs_type}}
deep_wp_thrs: # appears in discriminator init and apply selection
  e:
    "VVVLoose": 0.0630386
    "VVLoose": 0.1686942
    "VLoose": 0.3628130
    "Loose": 0.6815435
    "Medium": 0.8847544
    "Tight": 0.9675541
    "VTight": 0.9859251
    "VVTight": 0.9928449
  mu:
    "VLoose": 0.1058354
    "Loose": 0.2158633
    "Medium": 0.5551894
    "Tight": 0.8754835
  jet:
    "VVVLoose": 0.2599605
    "VVLoose": 0.4249705
    "VLoose": 0.5983682
    "Loose": 0.7848675
    "Medium": 0.8834768
    "Tight": 0.9308689
    "VTight": 0.9573137
    "VVTight": 0.9733927
