shared_cat_feature: 'particle_type'
shared_cat_dim_in: 10 # !!! reduce it accordingly in case of dropping particle blocks
shared_cat_dim_out: 2
r_cut: 0.5 # cut on delta R ("r" in current notation) to apply on all particle types, `null` to not apply
features_to_drop: # particle types must be ordered as they are yielded in TF dataset
  # list / "all" to drop the particle block altogether
  pfCand: [
            # 'fromPV', 'tauLeadChargedHadrCand',
            # 'hcalFraction', 'rawCaloFraction', 'rawHcalFraction', 
            # 'nHits', 'nPixelLayers', 'nStripLayers',
          ] 
  ele: [  
            # 'sigmaEtaEta', 'sigmaIetaIeta', 'sigmaIphiIphi', 'sigmaIetaIphi',
            # 'e1x5', 'e2x5Max', 'e5x5', 'r9', 
            # 'hcalDepth1OverEcal', 'hcalDepth2OverEcal', 'hcalDepth1OverEcalBc', 'hcalDepth2OverEcalBc',
            # 'eLeft', 'eRight', 'eBottom', 'eTop',
            # 'full5x5_sigmaEtaEta', 'full5x5_sigmaIetaIeta', 'full5x5_sigmaIphiIphi', 'full5x5_sigmaIetaIphi',
            # 'full5x5_e1x5', 'full5x5_e2x5Max', 'full5x5_e5x5', 'full5x5_r9',
            # 'full5x5_hcalDepth1OverEcal', 'full5x5_hcalDepth2OverEcal', 'full5x5_hcalDepth1OverEcalBc', 'full5x5_hcalDepth2OverEcalBc',
            # 'full5x5_eLeft', 'full5x5_eRight', 'full5x5_eBottom', 'full5x5_eTop',
            # 'full5x5_e2x5Left', 'full5x5_e2x5Right', 'full5x5_e2x5Bottom', 'full5x5_e2x5Top'
        ]
  muon: []
  global: [
          # 'tau_hasSecondaryVertex', 'tau_sv_minus_pv_x', 'tau_sv_minus_pv_y', 'tau_sv_minus_pv_z',
          ]
hidden_dim: [256, 256, 256, 256] # number of hidden nodes per each particle type in the order after dropping
activation: gelu
out_dim: 64